### PR TITLE
Add a minimal gitignore and remove xccheckout file

### PR DESCRIPTION
**Pull request by Abizern**

### CODE REVIEW

**Comment by danielctull** [comment]
What is the reasoning behind removing the xccheckout file? It's a shared resource…

I'm still undecided about whether I should or shouldn't be including them in projects, I'm wondering whether they aid in Bot functionality.

I'm also on a train so can't do any further research.

**Comment by Abizern** [comment]
Because the way the repository is set up in your Xcode project is not the way that it is set up in mine, or anyone else who clones your project.

It's basically local state, in the same way that the number of tabs you have open or your recent files list is not applicable to anyone else who clones your repository.

**Comment by danielctull** [comment]
The xccheckout file should be committed [according to Chris Hanson](http://stackoverflow.com/a/19260712/155863), though I'm still trying to work out if that's truly the case for library projects, as I agree with you it seems to be useless data. However, because it is in the `xcshareddata` I think I'm going to keep it in until I can fully mull this through.

I also think your .gitignore file is probably slightly flawed for ignoring anything in `project.xcworkspace/` because it will also ignore the `xcshareddata` when I may want to share schemes in the future.

**Comment by Abizern** [comment]
Shared schemes are not kept in that directory. They are in the top level of the xcodeproj directory. While you mention it, your build schemes aren't shared.

**Comment by danielctull** [comment]
My point is that there's no reason to ignore that whole directory as there's nothing to say it should be ignored. The user specific ones I agree with, but not shared data.

**Comment by danielctull** [comment]
I'm still interested in hearing why the xccheckout file should be ignored. What problem is it causing, and can it be rectified?

**Pull request closed without merging**
